### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by kb-elmo** [glizzy-goblin/gummy-60#1]
Since this project is based on the [original Bakeneko design](https://github.com/kkatano/bakeneko-60) by @kkatano it should be published under the same license as the original.

The [MIT license](https://en.wikipedia.org/wiki/MIT_License) (under which the original project was published) clearly states that any modified files of a project should only be redistributed under the same license.

Please include a copy of the MIT license in your project.
You can find it here https://github.com/kkatano/bakeneko-60/blob/develop/LICENSE

Failing to do so means that you are violating the original projects license.

**Comment by glizzy-goblin** [comment]
this keyboard is based on tgr singa unikorn.
